/**
 * Generates theme.css (the Tailwind v4 @theme block) from tokens.ts.
 *
 * Run: pnpm --filter @untch/design-tokens gen:theme
 *
 * tokens.ts is authoritative. theme.css is a build artifact. Never hand-edit it.
 * Emitting from one source keeps the CSS utilities and the TS manifest that the
 * specimen renders from in exact agreement (no drift between what is shown and
 * what components actually get).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  colors,
  typeScale,
  radii,
  shadows,
  layout,
  fontStack,
} from "./tokens";

const indent = "  ";
const lines: string[] = [];

lines.push("/*");
lines.push(" * GENERATED by src/gen-theme.ts from src/tokens.ts. Do not edit by hand.");
lines.push(" * Untch design tokens as a Tailwind v4 @theme block. Importing this file both");
lines.push(" * registers the CSS custom properties on :root and generates the matching");
lines.push(" * utilities (bg-*, text-*, rounded-*, shadow-*, etc.).");
lines.push(" *");
lines.push(" * `static` forces every token variable to emit even when unused, so any token");
lines.push(" * is referenceable by raw var() from anywhere (inline styles, JS). A foundation");
lines.push(" * is meant to be referenced, so it should not be tree-shaken.");
lines.push(" */");
lines.push("@theme static {");

lines.push(`${indent}/* Colors: raw Impilo tokens */`);
for (const c of colors) {
  lines.push(`${indent}${c.cssVar}: ${c.hex};`);
}

lines.push("");
lines.push(`${indent}/* Colors: Untch semantic aliases (see README "Open flag") */`);
for (const c of colors) {
  lines.push(`${indent}${c.semanticVar}: var(${c.cssVar});`);
}

lines.push("");
lines.push(`${indent}/* Typography: font stack (Manrope primary, Plus Jakarta Sans fallback) */`);
lines.push(`${indent}--font-untch: ${fontStack};`);
lines.push(`${indent}--font-sans: var(--font-untch);`);

lines.push("");
lines.push(`${indent}/* Typography: settled scale (Gilroy-tuned tracking; verify on Manrope) */`);
for (const t of typeScale) {
  lines.push(`${indent}--text-${t.name}: ${t.px}px;`);
  lines.push(`${indent}--text-${t.name}--line-height: ${t.lineHeight};`);
  lines.push(`${indent}--text-${t.name}--letter-spacing: ${t.letterSpacingPx}px;`);
  lines.push(`${indent}--text-${t.name}--font-weight: ${t.weight};`);
}

lines.push("");
lines.push(`${indent}/* Spacing: semantic layout tokens (numeric scale uses Tailwind's 4px base) */`);
lines.push(`${indent}--spacing-section: ${layout.sectionGap}px;`);
lines.push(`${indent}--spacing-card: ${layout.cardPadding}px;`);
lines.push(`${indent}--spacing-element: ${layout.elementGap}px;`);
lines.push(`${indent}--container-page: ${layout.pageMaxWidth}px;`);

lines.push("");
lines.push(`${indent}/* Border radius: canonical integer values, no fractional artifacts */`);
for (const r of radii) {
  lines.push(`${indent}${r.cssVar}: ${r.px}px;`);
}

lines.push("");
lines.push(`${indent}/* Shadow / elevation: cards carry no shadow; this glow is the only one */`);
for (const s of shadows) {
  lines.push(`${indent}${s.cssVar}: ${s.value};`);
}

lines.push("}");
lines.push("");

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "theme.css");
writeFileSync(outPath, lines.join("\n"), "utf8");
process.stdout.write(`Wrote ${outPath}\n`);
