// GENERATED by scripts/gen-workers-attestation.ts immediately before a Workers deploy.
// Do not edit, and do not commit a real attestation — it describes one deployment, not the branch.
import type { BuildAttestation } from "../deployment-info";

export const GENERATED_ATTESTATION: BuildAttestation | null = {
  "commit": "023518293720e464dff7afe48d837020e185e587",
  "branch": "feat/production-cutover",
  "builtAt": "2026-08-07T14:59:54.509Z",
  "source": "clean-git-export"
};
