// GENERATED by scripts/gen-workers-attestation.ts immediately before a Workers deploy.
//
// Checked in as `null` on purpose. A local `wrangler dev`, a CI bundle and any build that did not go
// through the deploy path all report honestly that they carry no attestation, and an unattested
// deployment is one that must not be armed. Only a real deploy replaces this, and the replacement is
// never committed — it describes one deployment, not the branch.
import type { BuildAttestation } from "../deployment-info";

export const GENERATED_ATTESTATION: BuildAttestation | null = null;
