import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { canonUint256 } from "../src/domain";
import { hashSpendIntent, type SpendIntent } from "../src/spendIntent";

/**
 * D0.5 differential generator (PRD §28 item 5). Reads the shared corpus
 * `fixtures/intents.json`, computes each case's Surface-B hash with `hashSpendIntent`, and
 * writes `fixtures/intents.hashes.json`. `contracts/test/IntentHash.t.sol` then recomputes
 * the same hashes on-struct in Solidity and asserts equality per case.
 *
 * The output is deterministic and committed; CI regenerates it and fails on any diff, so the
 * committed hashes are provably an honest function of the fixtures + this code.
 */

const FIXTURES = fileURLToPath(new URL("../../../fixtures/intents.json", import.meta.url));
const OUT = fileURLToPath(new URL("../../../fixtures/intents.hashes.json", import.meta.url));

const NUMERIC_POLICY =
  "All money amounts and uint256 values are carried as decimal STRINGS of integer base units, never JSON numbers.";

interface RawCase {
  name: string;
  owner: string;
  buyerAgentId: string;
  workerAgentId: string;
  token: string;
  maxAmount: string;
  taskHash: string;
  acceptanceHash: string;
  schemaHash: string;
  policyHash: string;
  deadline: string;
  nonce: string;
}

const ADDRESS_RE = /^0x[0-9a-fA-F]{40}$/;
const BYTES32_RE = /^0x[0-9a-fA-F]{64}$/;

function assertAddress(name: string, field: string, value: string): `0x${string}` {
  if (!ADDRESS_RE.test(value)) {
    throw new Error(`fixture "${name}".${field}: not a 42-char hex address: ${value}`);
  }
  return value as `0x${string}`;
}

function assertBytes32(name: string, field: string, value: string): `0x${string}` {
  if (!BYTES32_RE.test(value)) {
    throw new Error(`fixture "${name}".${field}: not a 66-char bytes32: ${value}`);
  }
  return value as `0x${string}`;
}

function toIntent(c: RawCase): SpendIntent {
  return {
    owner: assertAddress(c.name, "owner", c.owner),
    buyerAgentId: BigInt(canonUint256(c.buyerAgentId)),
    workerAgentId: BigInt(canonUint256(c.workerAgentId)),
    token: assertAddress(c.name, "token", c.token),
    maxAmount: BigInt(canonUint256(c.maxAmount)),
    taskHash: assertBytes32(c.name, "taskHash", c.taskHash),
    acceptanceHash: assertBytes32(c.name, "acceptanceHash", c.acceptanceHash),
    schemaHash: assertBytes32(c.name, "schemaHash", c.schemaHash),
    policyHash: assertBytes32(c.name, "policyHash", c.policyHash),
    deadline: BigInt(canonUint256(c.deadline)),
    nonce: BigInt(canonUint256(c.nonce)),
  };
}

function main(): void {
  const parsed = JSON.parse(readFileSync(FIXTURES, "utf8")) as { count: number; cases: RawCase[] };
  const cases = parsed.cases;

  if (!Array.isArray(cases) || cases.length !== parsed.count) {
    throw new Error(`fixtures: count ${parsed.count} != cases length ${cases?.length}`);
  }
  if (cases.length < 8) {
    throw new Error(`fixtures: D0.5 requires >=8 cases, found ${cases.length}`);
  }

  const seen = new Set<string>();
  const hashes = cases.map((c) => {
    if (seen.has(c.name)) throw new Error(`fixtures: duplicate case name "${c.name}"`);
    seen.add(c.name);
    return { name: c.name, hash: hashSpendIntent(toIntent(c)) };
  });

  const out = {
    _comment:
      "GENERATED by packages/canon/scripts/gen-fixture-hashes.ts from fixtures/intents.json — do not edit by hand. Surface-B keccak256(abi.encode(SpendIntent)) per §8.1; verified against Solidity IntentHash.hashIntent in contracts/test/IntentHash.t.sol.",
    numericPolicy: NUMERIC_POLICY,
    count: hashes.length,
    hashes,
  };

  writeFileSync(OUT, JSON.stringify(out, null, 2) + "\n");
  console.log(`NUMERIC POLICY: ${NUMERIC_POLICY}`);
  console.log(`wrote ${hashes.length} SpendIntent hashes -> ${OUT}`);
  for (const h of hashes) console.log(`  ${h.name.padEnd(28)} ${h.hash}`);
}

main();
