import assert from "node:assert/strict";
import { describe, test } from "node:test";
import manifest from "../src/workers/route-manifest.generated.json";
import { SERVICES } from "../src/registry/services";

/**
 * Every advertised service must be a route this host actually serves, at the method it advertises.
 *
 * `set_default_policy` was published as `POST /consumer/account/default-policy` and served as PUT. A
 * caller reading our own `/catalog` — or the MCP `tools/list` that a marketplace client plans from —
 * would send POST and get a 405 telling them the method they should have been given in the first
 * place. Nothing failed loudly; the entry was simply wrong, and had been for as long as it existed.
 *
 * The manifest is generated by CONSTRUCTING the Express app and walking its router stack, so it is
 * what will actually be served rather than what a regex found. That makes it the right thing to check
 * a published claim against.
 */

interface ManifestRoute {
  readonly method: string;
  readonly path: string;
}

/**
 * `{receiptId}` in the registry and `:receiptId` in Express are the same route in two notations — one
 * OpenAPI, one Express. Normalised so a comparison reports genuine drift rather than spelling.
 */
const normalise = (path: string): string => path.replace(/[:{]([A-Za-z0-9_]+)\}?/g, ":$1");

const served = new Map<string, Set<string>>();
for (const r of (manifest as { routes: ManifestRoute[] }).routes) {
  const key = normalise(r.path);
  served.set(key, (served.get(key) ?? new Set()).add(r.method.toUpperCase()));
}

describe("the registry advertises only what this host serves", () => {
  for (const service of SERVICES) {
    test(`${service.toolId} is served at ${service.method} ${service.path}`, () => {
      const methods = served.get(normalise(service.path));
      assert.ok(
        methods,
        `${service.toolId} advertises ${service.path}, which no route serves. A published path that ` +
          "404s is worse than an unpublished one: a client plans a call it can never make.",
      );
      assert.ok(
        methods.has(service.method.toUpperCase()),
        `${service.toolId} advertises ${service.method} but the route accepts ${[...methods].join(", ")}. ` +
          "A caller following the catalog would be refused for using the method the catalog gave them.",
      );
    });
  }
});
