import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SERVICES } from "../services/asp/src/registry/services";
import { buildOpenApi, buildWellKnownX402 } from "../services/asp/src/registry/openapi";
import { buildListingPayload, listingVerdict, threePartDescription } from "../services/asp/src/registry/listing";
import {
  RELISTING_INSTRUCTION,
  buildRelistingPayload,
  relistingServiceTable,
  reviewerInstructions,
  withheldSummary,
} from "../services/asp/src/registry/relisting-payload";
import { publicSchemaFor } from "../services/asp/src/registry/routes";
import { X_LAYER_MAINNET_ID, settlementToken } from "../packages/shared/src/index";

/**
 * Project the service registry into every artefact that used to be written by hand, and fail when
 * what is committed no longer matches what the registry says.
 *
 * The audit found the same contract in six places, none generated from another, and the only one that
 * was enforced disagreed with the other five. Generation alone does not fix that — a generator whose
 * output nobody checks just adds a seventh copy. The `--check` mode is the actual mechanism: CI runs
 * it, and a definition change that is not accompanied by regenerated artefacts fails the build.
 *
 * The artefacts are COMMITTED rather than built on demand for the same reason the chain registry is:
 * "what did this commit publish about its own contracts" has to be answerable from a diff. The OKX
 * listing payload in particular is a thing a human will read before submitting, and a file that only
 * exists after a build cannot be reviewed.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
export const GENERATED_DIR = join(ROOT, "services", "asp", "generated");

const BASE_URL = "https://asp.untch.xyz";
const NETWORK = `eip155:${X_LAYER_MAINNET_ID}`;
/**
 * The published payTo. It is a public address on a public chain and is already in every 402 challenge
 * and in the registration card; committing it here changes no exposure and keeps the generated
 * artefacts reproducible without a live environment.
 */
const PAY_TO = "0xD9eD4D474B0D01031d10d637546450F39ed6a5ba";

/**
 * The asset already stored on ASP #6086, verified 1024x1024 PNG, fully opaque, no rounded mask.
 *
 * A stable CDN URL rather than a repository path: the marketplace renders what this URL serves, so
 * the listing has to name the thing the marketplace will actually fetch.
 */
const PROFILE_PICTURE_URL =
  "https://static.okx.com/cdn/web3/wallet/marketplace/headimages/agent/avatar/c00d3425-c37e-4343-8a6a-5d25ca831278.png";

/** The installed @okxweb3/x402-express version, which is also the latest published one. */
const SDK_VERSION = "0.1.1";

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export interface GeneratedArtifact {
  readonly file: string;
  readonly content: string;
}

export function buildArtifacts(): readonly GeneratedArtifact[] {
  const token = settlementToken(X_LAYER_MAINNET_ID);
  const asset = { symbol: token.symbol, address: token.address, decimals: token.decimals };

  const openapi = buildOpenApi({ baseUrl: BASE_URL, network: NETWORK });
  const wellKnown = buildWellKnownX402({ baseUrl: BASE_URL, network: NETWORK, payTo: PAY_TO, asset });
  const listing = buildListingPayload({ baseUrl: BASE_URL, network: NETWORK, name: "Untch" });

  /**
   * The conformance fixtures.
   *
   * Every service contributes both directions: the request its contract says works, and one that its
   * real validator refuses, with the code it refuses with. A fixture set containing only valid cases
   * proves a validator accepts; it never proves one still rejects.
   */
  const fixtures = {
    $comment:
      "GENERATED by `pnpm gen:schemas`. One valid and one refused request per service, with the refusal code the live validator returns.",
    baseUrl: BASE_URL,
    cases: SERVICES.flatMap((s) => [
      {
        toolId: s.toolId,
        kind: "valid" as const,
        title: s.validExample.title,
        method: s.method,
        path: s.path,
        request: s.validExample.request,
      },
      {
        toolId: s.toolId,
        kind: "refused" as const,
        title: s.invalidExample.title,
        method: s.method,
        path: s.path,
        request: s.invalidExample.request,
        expectRefusalCode: s.invalidExample.refusalCode ?? null,
      },
    ]),
  };

  /** Every per-tool schema, exactly as `/schema/:tool` serves it, so a diff shows what a caller sees. */
  const schemas = {
    $comment: "GENERATED by `pnpm gen:schemas`. Byte-identical to what GET /schema/:tool serves.",
    tools: Object.fromEntries(SERVICES.map((s) => [s.toolId, publicSchemaFor(s, BASE_URL)])),
  };

  /**
   * The approval channels the listing may claim, and their real status.
   *
   * Stated here rather than derived, because "this channel works" is a live fact about credentials
   * and platform state that no local file knows. Discord is proven by two completed live approvals;
   * Telegram's stored bot credential answers 401 to `getMe`, so the listing says disabled rather
   * than claiming a channel a buyer could not reach.
   */
  const approvalChannels = [
    { channel: "discord", status: "live — delivery and one-tap approve/deny, proven against real requests" },
    { channel: "web", status: "live — signed single-use action links" },
    { channel: "telegram", status: "disabled — the stored bot credential is not authorised" },
  ];

  const relisting = buildRelistingPayload({
    payTo: PAY_TO,
    profilePictureUrl: PROFILE_PICTURE_URL,
    sdkVersion: SDK_VERSION,
    approvalChannels,
  });

  return [
    { file: "openapi.json", content: json(openapi) },
    { file: "well-known-x402.json", content: json(wellKnown) },
    { file: "okx-listing.json", content: json(listing) },
    { file: "conformance-fixtures.json", content: json(fixtures) },
    { file: "service-schemas.json", content: json(schemas) },
    { file: "SERVICE-CONTRACTS.md", content: renderMarkdown() },
    /**
     * The exact payload that updates the EXISTING ASP #6086.
     *
     * Generated for the same reason everything else here is: the submission that got two services
     * rejected was a markdown table pasted into a chat window, written by hand from a reading of the
     * code that had since moved. `buildRelistingPayload` refuses to produce a payload naming the
     * wrong ASP id or a temporary endpoint, so the identity check runs here rather than at submit
     * time — a payload that must not be sent should not exist as a file somebody could paste.
     */
    { file: "relisting-payload.json", content: json(relisting) },
    { file: "RELISTING.md", content: renderRelisting() },
  ];
}

/** The human-readable projection. Same source, so it cannot describe a different contract. */
function renderMarkdown(): string {
  const lines: string[] = [
    "# Untch service contracts",
    "",
    "GENERATED by `pnpm gen:schemas` from `services/asp/src/registry/services.ts`. Do not edit by hand.",
    "",
    "Every service this host offers a stranger's agent. Each entry is the same definition the runtime",
    "validator, the OpenAPI document, the x402 discovery document and the listing description are built",
    "from — so there is no version of this page that can disagree with the service.",
    "",
    "| Tool | Price | Maturity | Contract |",
    "| --- | --- | --- | --- |",
  ];
  for (const s of SERVICES) {
    const price = s.pricing.kind === "free" ? "free" : (s.pricing.price ?? "");
    lines.push(`| \`${s.toolId}\` | ${price} | ${s.maturity} | [/schema/${s.toolId}](${BASE_URL}/schema/${s.toolId}) |`);
  }
  lines.push("");

  for (const s of SERVICES) {
    const d = threePartDescription(s);
    const verdict = listingVerdict(s);
    lines.push(`## ${s.publicName} — \`${s.toolId}\``, "");
    lines.push(`\`${s.method} ${s.path}\` · ${s.pricing.kind === "free" ? "free" : `${s.pricing.price} per call`} · schema v${s.schemaVersion}`, "");
    lines.push(d.what, "", d.provide, "", d.receive, "");

    if (!verdict.listable) {
      lines.push("> **Not listable.** This service cannot be completed by a caller who does not already");
      lines.push("> hold something no public route produces:");
      for (const b of verdict.blockedBy) lines.push(`> - ${b}`);
      lines.push("");
    }

    if (s.predecessors.length > 0) {
      lines.push("**Must already exist**", "");
      for (const p of s.predecessors) {
        lines.push(`- ${p.what} ${p.why} ${p.obtainableBy ? `Obtain it with: ${p.obtainableBy}.` : "**No public route produces this.**"}`);
      }
      lines.push("");
    }

    if (s.sideEffects.length > 0) {
      lines.push("**What it changes**", "");
      for (const e of s.sideEffects) lines.push(`- ${e.what}${e.durable ? "" : " (does not outlive the request)"}`);
      lines.push("");
    }

    lines.push(`**Repeating an identical request:** ${s.idempotency}.`, "");
    lines.push("**Refusals**", "");
    for (const r of s.refusals) lines.push(`- \`${r.code}\` (${r.status}) — ${r.when}`);
    lines.push("");
    lines.push("**A request that works**", "", "```json", JSON.stringify(s.validExample.request, null, 2), "```", "");
    lines.push(
      `**A request that is refused** — \`${s.invalidExample.refusalCode ?? "refused"}\``,
      "",
      "```json",
      JSON.stringify(s.invalidExample.request, null, 2),
      "```",
      "",
    );
  }
  return `${lines.join("\n")}\n`;
}

function main(): void {
  const artifacts = buildArtifacts();
  const check = process.argv.includes("--check");

  if (check) {
    const drifted: string[] = [];
    for (const a of artifacts) {
      let onDisk: string | null = null;
      try {
        onDisk = readFileSync(join(GENERATED_DIR, a.file), "utf8");
      } catch {
        onDisk = null;
      }
      if (onDisk !== a.content) drifted.push(a.file);
    }
    if (drifted.length > 0) {
      console.error(
        `[gen:schemas] DRIFT in ${drifted.join(", ")}.\n` +
          "            The committed artefacts no longer match services/asp/src/registry/services.ts.\n" +
          "            Run `pnpm gen:schemas` and commit the result.",
      );
      process.exit(1);
      return;
    }
    console.log(`[gen:schemas] ok — ${artifacts.length} generated artefacts match the registry`);
    return;
  }

  mkdirSync(GENERATED_DIR, { recursive: true });
  for (const a of artifacts) writeFileSync(join(GENERATED_DIR, a.file), a.content);

  const listing = buildListingPayload({ baseUrl: BASE_URL, network: NETWORK, name: "Untch" });
  console.log(`[gen:schemas] wrote ${artifacts.length} artefacts to services/asp/generated/`);
  console.log(`[gen:schemas]   ${SERVICES.length} services · ${listing.service.length} listable · ${listing.withheld.length} withheld`);
  for (const w of listing.withheld) {
    console.log(`[gen:schemas]   withheld ${w.toolId}: ${w.blockedBy.join(" · ")}`);
  }
}

const isMain = process.argv[1] !== undefined && import.meta.url.endsWith(process.argv[1]);
if (isMain) main();

/** The relisting brief, generated so the reviewer instructions cannot describe a different service. */
function renderRelisting(): string {
  const payload = buildRelistingPayload({
    payTo: PAY_TO,
    profilePictureUrl: PROFILE_PICTURE_URL,
    sdkVersion: SDK_VERSION,
    approvalChannels: [
      { channel: "discord", status: "live — delivery and one-tap approve/deny, proven against real requests" },
      { channel: "web", status: "live — signed single-use action links" },
      { channel: "telegram", status: "disabled — the stored bot credential is not authorised" },
    ],
  });
  const withheld = withheldSummary();
  const paid = payload.services.filter((s) => s.paid);
  const free = payload.services.filter((s) => !s.paid);

  return [
    "# Untch — proposed relisting for existing OKX ASP #6086",
    "",
    "GENERATED by `pnpm gen:schemas`. Do not edit by hand.",
    "",
    "This updates the EXISTING ASP. It does not register a new one, and it never uses the ERC-8004",
    `agent id (${payload.erc8004.agentId}) in the ASP position.`,
    "",
    "| | |",
    "| --- | --- |",
    `| OKX ASP id | ${payload.aspId} |`,
    `| ASP type | ${payload.aspType} |`,
    `| ERC-8004 agent id | ${payload.erc8004.agentId} — on-chain identity only |`,
    `| Production URL | ${payload.productionUrl} |`,
    `| Docs | ${payload.docsUrl} |`,
    `| Network | ${payload.network} |`,
    `| Settlement token | ${payload.settlementToken.symbol} \`${payload.settlementToken.address}\` |`,
    `| payTo | \`${payload.payTo}\` |`,
    `| Payment SDK | ${payload.paymentSdk.middleware}@${payload.paymentSdk.version}, scheme \`${payload.paymentSdk.scheme}\` |`,
    `| Profile picture | ${payload.profilePicture.width}x${payload.profilePicture.height} ${payload.profilePicture.mimeType} |`,
    "",
    "## Description",
    "",
    payload.conciseDescription,
    "",
    payload.completeDescription,
    "",
    "Untch provides:",
    "",
    ...payload.capabilities.map((c) => `- ${c}`),
    "",
    "## Services",
    "",
    `${payload.services.length} listed — ${paid.length} paid, ${free.length} free.`,
    "",
    relistingServiceTable(payload),
    "",
    "## Approval channels",
    "",
    ...payload.approvalChannels.map((c) => `- **${c.channel}** — ${c.status}`),
    "",
    "## Not listed, and why",
    "",
    `${withheld.length} of this host's ${withheld.length + payload.services.length} services are deliberately not marketplace products.`,
    "",
    "| Service | Class | Reason |",
    "| --- | --- | --- |",
    ...withheld.map((w) => `| \`${w.toolId}\` | ${w.serviceClass} | ${w.reason} |`),
    "",
    "## Reviewer instructions",
    "",
    "```",
    reviewerInstructions(payload),
    "```",
    "",
    "## The relisting instruction",
    "",
    "```",
    RELISTING_INSTRUCTION,
    "```",
    "",
  ].join("\n");
}
