/**
 * Write the build attestation INTO the Workers source tree, from a clean git state.
 *
 * Run immediately before `wrangler deploy`. The generated constant is then bundled with the code it
 * describes, so the two cannot separate — which is the whole property. A deploy-time environment
 * variable would not have it: variables outlive the deployment that set them, and one claiming a
 * commit whose build failed is precisely the lie that made this mechanism necessary.
 *
 * REFUSES ON A DIRTY TREE
 *
 * An attestation naming a commit is a claim that the running code IS that commit. With uncommitted
 * changes in the bundle that claim is false, and a false attestation is worse than none, because the
 * absent case is already handled honestly as "unattested". So this exits non-zero instead, unless
 * `ALLOW_DIRTY_ATTESTATION=1` is set for a deliberate throwaway build.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGET = join(HERE, "..", "services", "asp", "src", "workers", "build-attestation.generated.ts");

const git = (...args: string[]): string => execFileSync("git", args, { encoding: "utf8" }).trim();

const HEADER = `// GENERATED by scripts/gen-workers-attestation.ts immediately before a Workers deploy.`;

/**
 * The checked-in state: no attestation at all.
 *
 * Written out literally rather than restored with `git checkout`, because the thing being guarded
 * against is a real attestation reaching the branch — and once one has, git is restoring the wrong
 * file. This is the definition, so `--reset` is correct even from a tree that already made that
 * mistake. It happened during the Cloudflare cutover: a `git add -A` between generating and deploying
 * swept a live attestation into a commit, and only a CI test noticed.
 */
const RESET = `${HEADER}
//
// Checked in as \`null\` on purpose. A local \`wrangler dev\`, a CI bundle and any build that did not go
// through the deploy path all report honestly that they carry no attestation, and an unattested
// deployment is one that must not be armed. Only a real deploy replaces this, and the replacement is
// never committed — it describes one deployment, not the branch.
import type { BuildAttestation } from "../deployment-info";

export const GENERATED_ATTESTATION: BuildAttestation | null = null;
`;

if (process.argv.includes("--reset")) {
  writeFileSync(TARGET, RESET);
  console.log("attestation reset to null");
  process.exit(0);
}

const dirty = git("status", "--porcelain");
if (dirty && process.env.ALLOW_DIRTY_ATTESTATION !== "1") {
  console.error("refusing to attest a dirty tree — the claim would be false:\n" + dirty);
  process.exit(1);
}

const attestation = {
  commit: git("rev-parse", "HEAD"),
  branch: git("rev-parse", "--abbrev-ref", "HEAD"),
  builtAt: new Date().toISOString(),
  source: dirty ? "dirty-tree (ALLOW_DIRTY_ATTESTATION=1)" : "clean-git-export",
};

writeFileSync(
  TARGET,
  `// GENERATED by scripts/gen-workers-attestation.ts immediately before a Workers deploy.
// Do not edit, and do not commit a real attestation — it describes one deployment, not the branch.
import type { BuildAttestation } from "../deployment-info";

export const GENERATED_ATTESTATION: BuildAttestation | null = ${JSON.stringify(attestation, null, 2)};
`,
);

console.log(`attestation written for ${attestation.commit.slice(0, 7)} (${attestation.source})`);
