import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CHAIN_REGISTRY, DEFAULT_CHAIN_ID } from "../packages/shared/src/chain-registry";

/**
 * Project the derived chain registry to JSON, and fail when the committed projection has drifted.
 *
 * WHY A JSON PROJECTION AT ALL
 *
 * The TypeScript registry is the source every service reads. But manifests, deployment checks and the
 * public-copy scanner are not all TypeScript, and a JSON file is the honest way to hand the same facts
 * to something that cannot import a module. The risk with any second copy is that it becomes a second
 * OPINION, so this one is generated, committed, and checked: `--check` exits non-zero when the file on
 * disk differs from what the registry says today, which is what CI runs.
 *
 * Committing the artefact rather than generating it at build time is deliberate. A generated file that
 * only exists after a build cannot be reviewed in a diff, and "which chains did this commit believe
 * in" is exactly the question the 195/1952 divergence made worth being able to answer from history.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
export const CHAIN_REGISTRY_JSON_PATH = join(HERE, "..", "packages", "shared", "generated", "chain-registry.json");

export function renderChainRegistry(): string {
  const payload = {
    $comment:
      "GENERATED by `pnpm gen:chains` from packages/shared/src/chain-registry.ts. Do not edit by hand — CI fails on drift.",
    defaultChainId: DEFAULT_CHAIN_ID,
    chains: CHAIN_REGISTRY,
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

function main(): void {
  const rendered = renderChainRegistry();
  const check = process.argv.includes("--check");

  if (check) {
    let onDisk: string;
    try {
      onDisk = readFileSync(CHAIN_REGISTRY_JSON_PATH, "utf8");
    } catch {
      console.error(`[gen:chains] MISSING ${CHAIN_REGISTRY_JSON_PATH} — run \`pnpm gen:chains\``);
      process.exit(1);
      return;
    }
    if (onDisk !== rendered) {
      console.error(
        "[gen:chains] DRIFT: packages/shared/generated/chain-registry.json does not match packages/shared/src/chain-registry.ts.\n" +
          "            Run `pnpm gen:chains` and commit the result.",
      );
      process.exit(1);
      return;
    }
    console.log("[gen:chains] ok — generated chain registry matches source");
    return;
  }

  mkdirSync(dirname(CHAIN_REGISTRY_JSON_PATH), { recursive: true });
  writeFileSync(CHAIN_REGISTRY_JSON_PATH, rendered);
  console.log(`[gen:chains] wrote ${CHAIN_REGISTRY_JSON_PATH} (${CHAIN_REGISTRY.length} chains)`);
}

const isMain = process.argv[1] !== undefined && import.meta.url.endsWith(process.argv[1]);
if (isMain) main();
