#!/usr/bin/env bash
# D0.5 evidence generator — runs every gate for real and writes the transcript. Re-runnable.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
OUT="$ROOT/internal/day0/D0.5-evidence/differential.txt"
cd "$ROOT"

rule() { printf '\n========================================================================\n%s\n========================================================================\n' "$1"; }

{
  echo "D0.5 — Canonicalization spike: two hashing surfaces, deterministic + cross-implementation identical"
  echo "PRD refs: §8.1 (SpendIntent) · §9 (canonicalization) · §28 item 5 (canon differential in CI) · §29 row D0.5"
  echo "Generated by: internal/day0/D0.5-evidence/run-transcript.sh"
  echo "Toolchain: $(node --version) node · pnpm $(pnpm --version) · $(forge --version | head -1)"
  echo
  echo "RESULT: PASS"
  echo "  - Surface A (RFC 8785 canonical JSON): RFC vectors green, §9 domain-rule tests green."
  echo "  - Surface B (SpendIntent struct hash): 15/15 differential cases green in forge (>=8 required)."
  echo "  - Cross-process determinism green. CI wired: canon.yml + contracts.yml (permanent, per §28)."
  echo
  echo "NUMERIC-POLICY DECISION (recorded in packages/canon/README.md + domain.ts):"
  echo "  All money amounts and all uint256 values are carried in canonical JSON as decimal STRINGS"
  echo "  of integer base units — NEVER JSON numbers. JSON numbers are IEEE-754 doubles: they lose"
  echo "  precision above 2^53 (a uint256 amount cannot survive one) and serialize differently across"
  echo "  languages. canonUint256() enforces this at runtime by rejecting JS numbers; moneyToBaseUnits()"
  echo "  converts display amounts to base units using the token's decimals from the verified list."
  echo
  echo "RFC 8785 EDGES RESOLVED:"
  echo "  1. Money-as-strings sidesteps the entire RFC 8785 number-formatting surface (es6testfile) for"
  echo "     every hash we take — canonicalization never depends on float serialization."
  echo "  2. Object-key ordering is by UTF-16 code unit, NOT code point. A non-BMP key like the grinning"
  echo "     emoji (U+1F600, first UTF-16 unit 0xD83D) sorts BEFORE a BMP key at U+F8FF (0xD83D < 0xF8FF),"
  echo "     opposite to code-point order. Pinned in test/rfc8785.vectors.test.ts."
  echo
  echo "IMPLEMENTATION NOTE: Surface A wraps the RFC 8785 reference implementation (canonicalize@3.0.0)"
  echo "and re-runs the RFC's own behaviors against the wrapper (per the D0.5 brief). Surface B uses viem"
  echo "encodeAbiParameters + keccak256; the Solidity side is keccak256(abi.encode(...)) — NOT encodePacked."
  echo
  echo "PRE-EXISTING TOOLCHAIN FIX (minimal, in-scope for CI coverage of the new file): contracts/.solhintignore"
  echo "had a bare 'lib/' pattern which (gitignore semantics) also excluded src/lib/, silently dropping"
  echo "src/lib/IntentHash.sol from the §28 solhint gate. Anchored the patterns to the contracts root"
  echo "(/lib/ etc.) so first-class library sources are linted. Verified below."

  rule "1. TS typecheck (tsc --noEmit) — Surface A + B + all tests"
  pnpm typecheck 2>&1

  rule "2. Canon TS suite — RFC 8785 vectors + §9 domain rules + cross-process determinism + Surface B corpus"
  pnpm test:canon 2>&1

  rule "3. Regenerate Surface B hashes from fixtures/intents.json (prints the numeric-policy line + hash table)"
  pnpm gen:fixtures 2>&1

  rule "4. Committed hashes are an honest, deterministic function of the fixtures (regen => no diff)"
  if git diff --quiet -- fixtures/intents.hashes.json 2>/dev/null; then
    echo "git diff fixtures/intents.hashes.json: NO DIFF (idempotent) [note: if untracked, honesty check first bites post-commit]"
  else
    echo "git diff fixtures/intents.hashes.json: DIFF PRESENT"; git --no-pager diff -- fixtures/intents.hashes.json
  fi
  git status --short -- fixtures/ 2>&1

  rule "5. Solidity differential — contracts/test/IntentHash.t.sol reads both fixture files, hashes on-struct, asserts equality for all 15 cases"
  ( cd contracts && forge test --match-contract IntentHashTest -vv 2>&1 )

  rule "6. Negative control — inject a field-order bug (swap deadline<->nonce) in IntentHash.sol; the single-field fixtures must catch it"
  cp contracts/src/lib/IntentHash.sol /tmp/D05_ih.bak
  perl -0pi -e 's/intent\.deadline,\n                intent\.nonce/intent.nonce,\n                intent.deadline/' contracts/src/lib/IntentHash.sol
  ( cd contracts && forge test --match-contract IntentHashTest 2>&1 | grep -E "FAIL|Suite result" )
  cp /tmp/D05_ih.bak contracts/src/lib/IntentHash.sol && rm /tmp/D05_ih.bak
  echo "(restored IntentHash.sol; confirming green again:)"
  ( cd contracts && forge test --match-contract IntentHashTest 2>&1 | grep -E "Suite result" )

  rule "7. Contracts static/style gates (the §28 pipeline that also governs IntentHash.sol)"
  echo "--- forge fmt --check ---"
  ( cd contracts && forge fmt --check 2>&1 && echo "fmt: CLEAN" )
  echo "--- forge build (solc 0.8.34, deny=warnings) ---"
  ( cd contracts && forge build 2>&1 | tail -3 )
  echo "--- solhint (src/lib/IntentHash.sol now covered after the ignore fix) ---"
  ( cd contracts && npm run lint 2>&1 | tail -4 ) && echo "solhint: CLEAN (exit 0)"

  rule "8. Full forge suite (Scaffold + IntentHash)"
  ( cd contracts && forge test 2>&1 | tail -8 )

  rule "END — D0.5 PASS"
} > "$OUT" 2>&1

echo "wrote $OUT"
